version: '3.4'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./DotNETCore.Identity.API.Presentation/Dockerfile
    ports:
      - "8080"
      - "8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
